from .patient import HospitalPatient,PatientScreening
from .res_config import Settings
from .sale import SaleOrder
from .appointment import HospitalAppointment
from .doctor import HospitalDoctor
from .user import HospitalUser
from .opd import HospitalOpd
from .test import HospitalTest
from .bill import HospitalBill
from .dashboard import Dashboard